# Generated by Django 5.2.8 on 2026-02-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_post_image_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='technology',
        ),
        migrations.AddField(
            model_name='post',
            name='habilidades',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
